# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-06 08:39
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Sys', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HappyLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='Create time')),
                ('update_time', models.DateTimeField(auto_now=True, null=True, verbose_name='Update time')),
                ('update_user', models.CharField(blank=True, max_length=200, null=True, verbose_name='Update user')),
                ('personal_happy_level', models.CharField(blank=True, choices=[('1', 'no happy'), ('2', 'normal'), ('3', 'happy')], max_length=50, null=True, verbose_name='personal happy level')),
                ('project_happy_level', models.CharField(blank=True, choices=[('1', 'no happy'), ('2', 'normal'), ('3', 'happy')], max_length=50, null=True, verbose_name='project happy level')),
                ('create_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Sys.Project')),
            ],
            options={
                'ordering': ['-create_time'],
                'permissions': (('query_happylevel', 'can query happy level'), ('export_happylevel', 'can export happy level')),
            },
        ),
    ]
