# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-28 06:59
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ProjectManagement', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HappyLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='Create time')),
                ('update_time', models.DateTimeField(auto_now=True, null=True, verbose_name='Update time')),
                ('personal_happy_level', models.CharField(blank=True, choices=[('1', 'Exited'), ('2', 'Happy'), ('3', 'Normal'), ('4', 'Unhappy'), ('5', 'Angry')], max_length=50, null=True, verbose_name='personal happy level')),
                ('project_happy_level', models.CharField(blank=True, choices=[('1', 'Exited'), ('2', 'Happy'), ('3', 'Normal'), ('4', 'Unhappy'), ('5', 'Angry')], max_length=50, null=True, verbose_name='project happy level')),
                ('create_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ProjectManagement.Project')),
                ('update_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='happylevel_updateuser', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-create_time'],
                'permissions': (('query_happylevel', 'can query happy level'), ('export_happylevel', 'can export happy level')),
            },
        ),
        migrations.CreateModel(
            name='TaskBatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='Task batch create time')),
            ],
        ),
        migrations.CreateModel(
            name='TaskState',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.CharField(blank=True, max_length=100, null=True, verbose_name='email')),
                ('task_state', models.CharField(blank=True, choices=[('1', 'undone'), ('2', 'done'), ('3', 'timeout')], max_length=50, null=True, verbose_name='task state level')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ProjectManagement.Project')),
                ('task_batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='HappyManagement.TaskBatch')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': [],
                'permissions': (('query_taskstate', 'can query task state'), ('export_taskstate', 'can export task state')),
            },
        ),
    ]
