# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-07 00:30
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HappyManagement', '0002_auto_20180906_2122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='happylevel',
            name='update_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='happylevel_updateuser', to=settings.AUTH_USER_MODEL),
        ),
    ]
